/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 salad.glb 
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/salad.glb')
  const modelRef = useRef();

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.005; // Adjust rotation speed as needed
    }
  });

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <mesh geometry={nodes.plate.geometry} material={materials.main} position={[0.039, 1.545, -0.217]} rotation={[Math.PI / 2, 0, 0]} scale={3.085} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-0.252, 1.684, -0.318]} rotation={[0.777, 0.934, -0.538]} scale={[-0.02, 0, -0.02]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[-0.283, 1.693, -0.308]} rotation={[0.848, 0.864, -0.607]} scale={[-0.009, 0, -0.009]} />
      <mesh geometry={nodes.pCylinder6.geometry} material={materials.blinn1} rotation={[Math.PI / 2, 0, 0]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/salad.glb')
